export const FETCH_PROMOTION = 'FETCH_PROMOTION';
export const FETCH_PROMOTION_SUCCESS = 'FETCH_PROMOTION_SUCCESS';
export const FETCH_PROMOTION_FAIL = 'FETCH_PROMOTION_FAIL';

export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const UPDATE_PROMOTION_SUCCESS = 'UPDATE_PROMOTION_SUCCESS';
export const UPDATE_PROMOTION_FAIL = 'UPDATE_PROMOTION_FAIL';