export const FETCH_PARTNER = 'FETCH_PARTNER';
export const FETCH_PARTNER_SUCCESS = 'FETCH_PARTNER_SUCCESS';
export const FETCH_PARTNER_FAIL = 'FETCH_PARTNER_FAIL';

export const UPDATE_PARTNER = 'UPDATE_PARTNER';
export const UPDATE_PARTNER_SUCCESS = 'UPDATE_PARTNER_SUCCESS';
export const UPDATE_PARTNER_FAIL = 'UPDATE_PARTNER_FAIL';
