export const UPDATE_PARTNER = 'UPDATE_PARTNER';
export const UPDATE_PARTNER_SUCCESS = 'UPDATE_PARTNER_SUCCESS';
export const UPDATE_PARTNER_FAIL = 'UPDATE_PARTNER_FAIL';

export const PARTNER_SIGNIN = 'PARTNER_SIGNIN';
export const PARTNER_SIGNIN_SUCCESS = 'PARTNER_SIGNIN_SUCCESS';
export const PARTNER_SIGNIN_FAIL = 'PARTNER_SIGNIN_FAIL';

export const MLTS = 'MLTS';