export const UPDATE_PARTNER = 'UPDATE_PARTNER';
export const UPDATE_PARTNER_SUCCESS = 'UPDATE_PARTNER_SUCCESS';
export const UPDATE_PARTNER_FAIL = 'UPDATE_PARTNER_FAIL';

export const PARTNER_SIGNIN = 'PARTNER_SIGNIN';
export const PARTNER_SIGNIN_SUCCESS = 'PARTNER_SIGNIN_SUCCESS';
export const PARTNER_SIGNIN_FAIL = 'PARTNER_SIGNIN_FAIL';

export const MLTS = 'MLTS';
export const SIGN_OUT = 'SIGN_OUT';

export const PARTNER_CHANGE_IMAGE = 'PARTNER_CHANGE_IMAGE';
export const PARTNER_CHANGE_IMAGE_SUCCESS = 'PARTNER_CHANGE_IMAGE_SUCCESS';
export const PARTNER_CHANGE_IMAGE_FAIL = 'PARTNER_CHANGE_IMAGE_FAIL';